[project]
name = "mcp-hsm"
version = "0.1.0"
description = "A MCP server project to handle cryptographic operations with Hardware Security Module (HSM) Implementation"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.6.0",
]
